version: "3"
services:
    webserver:
        build: .
        container_name: apache-php-buzzvel
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./:/var/www/html
            - /etc/timezone:/etc/timezone
        ports:
            - "80:80"
        depends_on:
            - postgres
        restart: always

    postgres:
        image: postgres:13
        container_name: pgsql-buzzvel
        volumes:
            - /etc/timezone:/etc/timezone
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        restart: always

